### ISSUE TITLE
jibx issue with weblogic 12.1.3

### ISSUE THREAD

**Issue by abhishektechm** [jibx/jibx#4]
I am getting below exception while using jibx 1.2.3 with weblogic 12.1.3 in my application & java 1.7 on linux RHEL 6.3.Application working fine if I am using weblogic 12.1.1.Please suggest.

Exception: org.jibx.runtime.JiBXException: Missing required attribute "SchemaReference" 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
[ACTIVE] ExecuteThread: '59' for queue: 'weblogic.kernel.Default (self-tuning)' 2015-06-04 22:33:31,155 =ERROR (JIBXBindingResolver.java:111) - JiBXException occured 
org.jibx.runtime.JiBXException: Missing required attribute "SchemaReference" (line 1, col 139) 
at org.jibx.runtime.impl.UnmarshallingContext.attributeText(UnmarshallingContext.java:975) 
at au.com.vha.serviceapp.xsd.datatype.jibx.v1.serviceAppTransaction.ServiceRequest.JiBX_serviceAppTransaction_unmarshalAttr_1_0(Unknown Source) 
at au.com.vha.serviceapp.xsd.datatype.jibx.v1.serviceAppTransaction.JiBX_serviceAppTransactionServiceRequest_access.unmarshal() 
at org.jibx.runtime.impl.UnmarshallingContext.unmarshalElement(UnmarshallingContext.java:2757) 
at org.jibx.runtime.impl.UnmarshallingContext.unmarshalDocument(UnmarshallingContext.java:2914) 
at au.com.vha.serviceapp.common.jibx.parsing.JIBXBindingResolver.parseXml(JIBXBindingResolver.java:108) 
at au.com.vha.serviceapp.rest.ServiceAppResource.executeRequestResponse(ServiceAppResource.java:179) 
at au.com.vha.serviceapp.rest.ProductResource.getProducts(ProductResource.java:50) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:606) 
at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) 
at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ObjectOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:258) 
at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) 
at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) 
at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) 
at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) 
at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) 
at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) 
at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) 
at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) 
at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) 
at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) 
at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) 
at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) 
at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)

**Comment by smilep** [comment]
I am facing the same issue. When can we expect a fix for this please?
