### ISSUE TITLE
JIBX giving problem after upgrade to java 8

### ISSUE THREAD

**Issue by navnitsarda** [jibx/jibx#5]
I upgraded from jdk 7 to jdk 8. Started getting following problem.

Exception in thread "main" java.lang.IllegalStateException: Internal error: instance signatures not found for class java.lang.String
        at org.jibx.binding.model.ClassWrapper.isImplements(ClassWrapper.java:135)
        at org.jibx.custom.classes.SharedValueBase.fillType(SharedValueBase.java:367)
        at org.jibx.custom.classes.ValueCustom.fillDetails(ValueCustom.java:316)
        at org.jibx.custom.classes.ClassCustom.apply(ClassCustom.java:800)
        at org.jibx.custom.classes.GlobalCustom.addClassCustomization(GlobalCustom.java:377)
        at org.jibx.binding.generator.BindGen.checkInclude(BindGen.java:163)
        at org.jibx.binding.generator.BindGen.expandReferences(BindGen.java:208)
        at org.jibx.binding.generator.BindGen.findReferences(BindGen.java:1010)
        at org.jibx.binding.generator.BindGen.generate(BindGen.java:1124)
        at org.jibx.binding.generator.BindGen.main(BindGen.java:1302)

Any idea how can I resolve this issue.

**Comment by passyt** [comment]
I have re-code the binding part of Jibx with Javassist, and it support JDK1.8. See my project: https://github.com/passyt/jibx-bind

**Comment by doncorley** [comment]
JiBX 1.31. has been release with full JDK 1.8 support.
Problem solved!
